CREATE TABLE `USER` (
    verification VARCHAR(32) NOT NULL,
	firstname VARCHAR(20) NOT NULL,
	lastname VARCHAR(20) NOT NULL,
	email VARCHAR(60) NOT NULL PRIMARY KEY, 
	`password` VARCHAR(50) NOT NULL,
    accountType ENUM('ADV', 'ADMIN', 'UNKNOWN')
);

CREATE TABLE `LOGFILE` (
    token VARCHAR(32) NOT NULL PRIMARY KEY,
    user_id VARCHAR(60) NOT NULL,
    start_timestamp VARCHAR(10) NOT NULL, 
    end_timestamp VARCHAR(10) NOT NULL
);

CREATE TABLE `MODEL` (
  `id` bigint(20)  NOT NULL AUTO_INCREMENT Primary Key,
  `title` varchar(50) COLLATE utf8_bin NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `PENDING_RESULTS` (
	id VARCHAR(32) PRIMARY KEY,
    results TEXT
);