DROP TABLE `USER`;
DROP TABLE `TESTSET`;
DROP TABLE `TRAINSET`;
DROP TABLE `PARAMETER_FILE`;
DROP TABLE `LOGFILE`;
DROP TABLE `MODEL`;
DROP TABLE `TRAIN_ALGORITHM`;
DROP TABLE `PENDING_RESULTS`;

TRUNCATE TABLE `PENDING_RESULTS`;