DROP TABLE `USER`;
DROP TABLE `LOGFILE`;
DROP TABLE `MODEL`;
DROP TABLE `PENDING_RESULTS`;

TRUNCATE TABLE `PENDING_RESULTS`;
TRUNCATE TABLE `USER`;
TRUNCATE TABLE webApp.`LOGFILE`;
TRUNCATE TABLE `MODEL`;

-- NOT IN USE 
-- DROP TABLE `TESTSET`;
-- DROP TABLE `TRAINSET`;
-- DROP TABLE `PARAMETER_FILE`;
-- DROP TABLE `TRAIN_ALGORITHM`;